version: '3.4'

networks:
  kek:
    driver: bridge

services:
  iwor.api:
    image: ${DOCKER_REGISTRY-}iworapi
    build:
      context: .
      dockerfile: iwor.api/Dockerfile
    environment:
        ASPNETCORE_URLS: "https://+:443;http://+:80"
        ASPNETCORE_HTTPS_PORT: "44358"
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - kek
  db:
    image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
    environment:
        SA_PASSWORD: "123qweA!"
        ACCEPT_EULA: "Y"
    ports:
      - "3228:1433"
    networks:
      - kek